DELETE FROM public.articles;

INSERT INTO public.articles (slug, title, category, excerpt, body, author, image_alt, status, published_at) VALUES
('what-is-ai-really', 'What Is AI, Really? A Plain-English Explanation', 'ai',
 'Sample post: a jargon-free explanation of what today''s AI models actually do, where they help, and where they quietly fail.',
 E'Sample content — replace before launch.\n\nModern AI tools are pattern machines. They read enormous amounts of text, learn which words tend to follow which, and use that to produce answers that sound plausible. That is genuinely useful for drafting, summarising and explaining — and genuinely risky when you need a fact you cannot verify.\n\nA useful mental model: treat AI like a fast, confident intern. Great at first drafts, structure and boilerplate. Never the final word on numbers, dates, medical or legal detail.\n\nWhat to do next: pick one task you repeat weekly, ask an AI tool to do the first 60 percent, then edit. That is where the time saving lives.',
 'Pugclicks Staff', 'Illustration of a simple neural network explained with labels', 'published', now() - interval '1 day'),
('best-free-ai-tools', 'Best Free AI Tools Worth Using Right Now', 'ai',
 'Sample post: a short list of free AI tools that solve real problems — writing, research, images and transcription — with what each is best at.',
 E'Sample content — replace before launch.\n\nFree tiers change often, so judge a tool by the job it does rather than the brand. For writing and research, look for a model with good long-context handling. For images, look for consistent style control. For transcription, accuracy on accented speech matters more than speed.\n\nA reasonable free stack: one general assistant, one transcription tool, one image tool, one note app that can search your own material.\n\nAvoid stacking five tools that overlap. Two tools you use daily beat ten you forget.',
 'Pugclicks Staff', 'Grid of AI tool logos placeholder', 'published', now() - interval '3 day'),
('how-to-write-better-ai-prompts', 'How to Write Better AI Prompts (Without Memorising Tricks)', 'guides',
 'Sample post: prompting is mostly clear briefing. Four habits that reliably improve output, no magic phrases required.',
 E'Sample content — replace before launch.\n\nGive the role, the goal, the constraints and the format. That is 90 percent of prompting. "Write something about study planning" gets vague output. "You are a study coach. Make a 5-day revision plan for a Class 12 physics exam. 30-minute blocks. Return a table." gets something usable.\n\nThen iterate: keep the parts that worked and correct one thing at a time. Long prompt rewrites hide which change helped.\n\nFinally, ask the tool to show its assumptions before it produces the final answer. It surfaces misunderstandings early.',
 'Pugclicks Staff', 'Person typing a structured prompt on a laptop', 'published', now() - interval '5 day'),
('automate-repetitive-tasks', 'How to Automate Repetitive Tasks in One Afternoon', 'automation',
 'Sample post: find the three clicks you repeat every day and remove them with a simple, reliable automation.',
 E'Sample content — replace before launch.\n\nStart by logging your week. Anything you do more than three times with the same inputs is an automation candidate: saving attachments, renaming files, copying form responses into a sheet, sending the same follow-up.\n\nBuild the smallest version first — one trigger, one action. Test with real data. Add a failure notification so silent breakage does not cost you a week.\n\nThe goal is not a clever workflow. It is a boring workflow you never think about again.',
 'Pugclicks Staff', 'Diagram of a simple two-step automation workflow', 'published', now() - interval '7 day'),
('build-your-first-ai-workflow', 'Build Your First AI Workflow, Step by Step', 'automation',
 'Sample post: connect a trigger, an AI step and a destination to turn messy input into a clean, usable output automatically.',
 E'Sample content — replace before launch.\n\nA workflow is three parts: something happens, AI processes it, the result lands somewhere useful. Example: a new voice note arrives, it is transcribed and summarised, the summary is appended to your notes app with a date.\n\nKeep the AI step narrow. One instruction, one output shape. Broad instructions produce output your next step cannot parse.\n\nAdd a human checkpoint anywhere the output is published externally. Automation should reduce work, not accountability.',
 'Pugclicks Staff', 'Flowchart of trigger, AI step and destination', 'published', now() - interval '9 day'),
('android-settings-worth-changing', 'Android Settings Worth Changing on Day One', 'tech',
 'Sample post: a handful of settings that improve battery, privacy and daily speed on almost any Android phone.',
 E'Sample content — replace before launch.\n\nStart with permissions: revoke location for anything that is not a map, and set the rest to "ask every time". Then turn on adaptive battery and cap background activity for the apps you only open weekly.\n\nSwitch notification categories off per-app rather than muting whole apps — you keep the messages that matter.\n\nFinally, set up an automatic backup and check it actually ran. Backups you have not verified are wishes, not backups.',
 'Pugclicks Staff', 'Android settings screen placeholder', 'published', now() - interval '11 day'),
('phone-apps-that-earn-their-space', 'Phone Apps That Actually Earn Their Space', 'tech',
 'Sample post: how to judge an app in five minutes, and the categories worth keeping on a small home screen.',
 E'Sample content — replace before launch.\n\nGood apps do one job with predictable behaviour, work offline where it matters, and do not demand permissions unrelated to their purpose. If an app asks for contacts to show you a calculator, delete it.\n\nKeep one app per job: notes, tasks, reading, files, transit. Duplicates create decision fatigue and split your data.\n\nReview monthly. Anything unopened in four weeks goes.',
 'Pugclicks Staff', 'Minimal phone home screen with a few apps', 'published', now() - interval '13 day'),
('ai-study-tools-for-students', 'AI Study Tools That Actually Help Students', 'student-tech',
 'Sample post: using AI for revision without outsourcing the thinking — active recall, explanations and practice questions.',
 E'Sample content — replace before launch.\n\nThe wrong use of AI is asking for answers. The right use is asking for practice: generate ten questions from this chapter, mark my attempt, explain what I got wrong in simpler terms.\n\nCombine it with spaced repetition. Ask the tool to turn your weak answers into flashcards, then review them across days rather than in one long session.\n\nKeep your own notes as the source of truth. AI is the tutor, not the textbook.',
 'Pugclicks Staff', 'Student revising with a laptop and notebook', 'published', now() - interval '15 day'),
('free-tech-stack-for-students', 'A Free Tech Stack for Students', 'student-tech',
 'Sample post: notes, storage, PDFs, citations and focus — a complete study setup that costs nothing.',
 E'Sample content — replace before launch.\n\nPick one note app with fast search, one cloud folder with a clear naming rule, one PDF reader with annotation, one citation manager, and one focus timer. That is the whole stack.\n\nThe naming rule matters more than the tools: subject, topic, date. Future you searches, not browses.\n\nBack up before exam season, not during it.',
 'Pugclicks Staff', 'Desk setup with laptop, notes and headphones', 'published', now() - interval '17 day'),
('how-to-fact-check-ai-output', 'How to Fact-Check AI Output in Two Minutes', 'guides',
 'Sample post: a fast, repeatable check that catches most confident-sounding AI mistakes before you publish or submit.',
 E'Sample content — replace before launch.\n\nPull out every specific claim: numbers, names, dates, quotes. Those are where AI fails. Verify each against one primary source — the official site, the paper, the documentation.\n\nIf a source cannot be found in a minute, cut the claim. Unverifiable detail adds risk without adding value.\n\nKeep a note of what you checked. It makes corrections honest and fast.',
 'Pugclicks Staff', 'Checklist beside a laptop showing verification steps', 'published', now() - interval '19 day'),
('ai-agents-explained-simply', 'AI Agents Explained Simply (Draft)', 'ai',
 'Sample draft: what people mean by an AI agent, what agents can reliably do today, and what is still marketing.',
 E'Sample draft content — this post is unpublished and demonstrates the draft workflow in the editor dashboard.\n\nAn agent is a model plus tools plus a loop: it decides, acts, observes the result and tries again. That loop is what separates an agent from a chat reply.\n\nToday agents work well on narrow, verifiable tasks with clear success conditions. They work badly on open-ended goals with no feedback signal.',
 'Pugclicks Staff', 'Abstract diagram of an agent loop', 'draft', NULL);